FROM oven/bun:1 AS base

WORKDIR /app

# Prisma / DB config for build-time evaluation
ENV DATABASE_HOST="dummy"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="dummy"
ENV DATABASE_PASSWORD="dummy"
ENV DATABASE_NAME="dummy"

# --------------------------------------------------
# Dependencies
# --------------------------------------------------

FROM base AS deps

COPY package.json bun.lock ./

COPY apps/bot/package.json ./apps/bot/package.json
COPY apps/web/package.json ./apps/web/package.json

COPY packages/database/package.json ./packages/database/package.json

RUN bun install --frozen-lockfile

# --------------------------------------------------
# Builder
# --------------------------------------------------

FROM base AS builder

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules

COPY package.json bun.lock ./

COPY apps/web ./apps/web
COPY packages/database ./packages/database

COPY prisma.config.ts ./
COPY tsconfig.json ./

# Prisma Client
RUN bun --cwd packages/database db:generate

# Next.js build
RUN bun build:web


# --------------------------------------------------
# Runtime
# --------------------------------------------------

FROM oven/bun:1-slim AS runner

WORKDIR /app

COPY certs/ ./certs/

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/web/.next/standalone ./

COPY --from=builder /app/apps/web/.next/static \
  ./apps/web/.next/static

COPY --from=builder /app/apps/web/public \
  ./apps/web/public

EXPOSE 3000

CMD ["bun", "apps/web/server.js"]