FROM oven/bun:1 AS base

WORKDIR /app

ENV DATABASE_HOST="dummy"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="dummy"
ENV DATABASE_PASSWORD="dummy"
ENV DATABASE_NAME="dummy"

# --------------------------------------------------
# Dependencies
# --------------------------------------------------

FROM base AS deps

COPY package.json bun.lock ./

COPY apps/bot/package.json ./apps/bot/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/database/package.json ./packages/database/package.json

RUN bun install --frozen-lockfile

# DEBUG
RUN ls -la node_modules/.bin/next
RUN node_modules/.bin/next --version

# --------------------------------------------------
# Builder
# --------------------------------------------------

FROM base AS builder

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules

COPY package.json bun.lock ./
COPY apps/web ./apps/web
COPY packages/database ./packages/database
COPY prisma.config.ts ./
COPY tsconfig.json ./

RUN bun --cwd packages/database db:generate

RUN bun --cwd apps/web exec next --version

RUN bun build:web