FROM oven/bun:1 AS builder

WORKDIR /app

ENV DATABASE_HOST="dummy"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="dummy"
ENV DATABASE_PASSWORD="dummy"
ENV DATABASE_NAME="dummy"

ENV NEXT_TELEMETRY_DISABLED=1

# package manifests
COPY package.json bun.lock ./
COPY apps/bot/package.json ./apps/bot/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/database/package.json ./packages/database/package.json

# Install dependencies
RUN bun install --frozen-lockfile

# Source
COPY apps/web ./apps/web
COPY packages/database ./packages/database
COPY prisma.config.ts ./
COPY tsconfig.json ./

# Prisma
RUN bun --cwd packages/database db:generate

# Next.js
RUN bun build:web


# --------------------------------------------------
# Runtime
# --------------------------------------------------

FROM oven/bun:1-slim AS runner

WORKDIR /app

COPY certs/ ./certs/

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/web/.next/standalone ./

COPY --from=builder /app/apps/web/.next/static \
  ./apps/web/.next/static

COPY --from=builder /app/apps/web/public \
  ./apps/web/public

EXPOSE 3000

CMD ["bun", "apps/web/server.js"]