FROM oven/bun:1.3-slim AS base

WORKDIR /app

ENV DATABASE_HOST="dummy"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="dummy"
ENV DATABASE_PASSWORD="dummy"
ENV DATABASE_NAME="dummy"


# --------------------------------------------------
# Dependencies
# --------------------------------------------------

FROM base AS deps

# Root
COPY package.json bun.lock ./

# All workspace package.json
COPY apps/bot/package.json ./apps/bot/package.json
COPY apps/web/package.json ./apps/web/package.json

COPY packages/database/package.json ./packages/database/package.json

COPY .npmrc ./.npmrc

RUN bun install


# --------------------------------------------------
# Builder
# --------------------------------------------------

FROM base AS builder

COPY --from=deps /app/node_modules ./node_modules

COPY package.json bun.lock ./

COPY apps/bot ./apps/bot
COPY apps/web/package.json ./apps/web/package.json

COPY packages/database ./packages/database

COPY prisma.config.ts ./
COPY tsconfig.json ./

RUN bun --cwd packages/database db:generate

# --------------------------------------------------
# Runtime
# --------------------------------------------------

FROM oven/bun:1-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/apps/bot ./apps/bot
COPY --from=builder /app/packages/database ./packages/database

COPY certs/ ./certs/

CMD ["sh", "-c", "bun --cwd packages/database db:migrate && bun apps/bot/src/index.ts"]